#!/bin/csh

source ../common/setenvvars

SERVER_NAME=${SERVER_NAME:-Director}

SERVER_HOST=${HOST}
SERVER_BIND=${HOST}

PORT_OPEN=$(( DIRE_PORT_BASE     ))
PORT_PSWD=$(( DIRE_PORT_BASE + 1 ))

${JAVA_RUN} org.elkoserver.foundation.boot.Boot \
   trace_dire=DEBUG \
   trace_comm=WORLD \
   tracelog_tag=director \
   tracelog_dir=${TRACE_DIR} \
   \
   conf.listen.host=${SERVER_HOST}:${PORT_OPEN} \
   conf.listen.bind=${SERVER_BIND}:${PORT_OPEN} \
   conf.listen.auth.mode=open \
   conf.listen.allow=user \
   \
   conf.listen1.host=${SERVER_HOST}:${PORT_PSWD} \
   conf.listen1.bind=${SERVER_BIND}:${PORT_PSWD} \
   conf.listen1.auth.mode=open \
   conf.listen1.allow=any \
   \
   conf.director.name=${SERVER_NAME} \
   conf.comm.jsonstrictness=true \
   conf.msgdiagnostics=true \
   org.elkoserver.server.director.DirectorBoot \
   $*

