#!/bin/csh

source ../common/setenvvars

if (! ${?SERVER_NAME}) then
   set SERVER_NAME=Director
endif

if (! ${?LOG_TAG}) then
   set LOG_TAG=dire
endif

set SERVER_HOST=${HOST}
set SERVER_BIND=${HOST}

@ PORT_CLIENT_TCP  = ${DIRE_PORT_BASE}
@ PORT_CLIENT_RTCP = ${DIRE_PORT_BASE} + 1
@ PORT_SERVER_TCP  = ${DIRE_PORT_BASE} + 2

@ BROKER_PORT = ${BROK_PORT_BASE} + 1

${JAVA_RUN} org.elkoserver.foundation.boot.Boot \
   trace_dire=EVENT \
   trace_comm=EVENT \
   tracelog_tag=${LOG_TAG} \
   tracelog_dir=${TRACE_DIR} \
   \
   conf.listen.host=${SERVER_HOST}:${PORT_CLIENT_TCP} \
   conf.listen.bind=${SERVER_BIND}:${PORT_CLIENT_TCP} \
   conf.listen.auth.mode=open \
   conf.listen.allow=user \
   conf.listen.protocol=tcp \
   \
   conf.listen1.host=${SERVER_HOST}:${PORT_CLIENT_RTCP} \
   conf.listen1.bind=${SERVER_BIND}:${PORT_CLIENT_RTCP} \
   conf.listen1.auth.mode=open \
   conf.listen1.allow=user \
   conf.listen1.protocol=rtcp \
   \
   conf.listen2.host=${SERVER_HOST}:${PORT_SERVER_TCP} \
   conf.listen2.bind=${SERVER_BIND}:${PORT_SERVER_TCP} \
   conf.listen2.auth.mode=open \
   conf.listen2.allow=any \
   conf.listen2.protocol=tcp \
   \
#   conf.broker.host=${SERVER_HOST}:${BROKER_PORT} \
   \
   conf.director.name=${SERVER_NAME} \
   conf.comm.jsonstrictness=true \
   conf.msgdiagnostics=true \
   org.elkoserver.server.director.DirectorBoot \
   $*

